name: emb-diachronic
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - blas=1.0
  - ca-certificates=2025.2.25
  - intel-openmp=2023.1.0
  - libffi=3.4.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - numpy=1.21.6
  - numpy-base=1.21.6
  - openssl=3.0.16
  - pip=24.2
  - python=3.8.20
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - vc=14.42
  - vs2015_runtime=14.42.34433
  - wheel=0.44.0
  - pip:
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - idna==3.10
      - pillow==10.4.0
      - requests==2.32.3
      - torch==1.12.1+cu116
      - torchvision==0.13.1+cu116
      - typing-extensions==4.13.2
      - urllib3==2.2.3
