name: gnn-evokg
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - ca-certificates=2025.2.25
  - libffi=3.4.4
  - openssl=3.0.16
  - pip=24.2
  - python=3.8.20
  - setuptools=75.1.0
  - sqlite=3.45.3
  - vc=14.42
  - vs2015_runtime=14.42.34433
  - wheel=0.44.0
  - pip:
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - async-timeout==5.0.1
      - attrs==25.3.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - colorama==0.4.6
      - dgl==1.1.2+cu116
      - dill==0.4.0
      - frozenlist==1.5.0
      - fsspec==2025.3.0
      - idna==3.10
      - jinja2==3.1.6
      - markupsafe==2.1.5
      - multidict==6.1.0
      - networkx==3.1
      - numpy==1.24.4
      - packaging==25.0
      - pandas==2.0.3
      - pillow==10.4.0
      - propcache==0.2.0
      - psutil==7.0.0
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - requests==2.32.3
      - scipy==1.10.1
      - six==1.17.0
      - torch==1.12.1+cu116
      - torch-geometric==2.6.1
      - torch-scatter==2.0.9
      - torchaudio==0.12.1+cu116
      - torchvision==0.13.1+cu116
      - tqdm==4.67.1
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - urllib3==2.2.3
      - yarl==1.15.2
