name: gnn-retemp
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - ca-certificates=2025.2.25
  - openssl=3.0.16
  - pip=25.0
  - python=3.9.21
  - setuptools=75.8.0
  - sqlite=3.45.3
  - vc=14.42
  - vs2015_runtime=14.42.34433
  - wheel=0.45.1
  - pip:
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - colorama==0.4.6
      - dgl==1.1.2+cu118
      - filelock==3.18.0
      - fsspec==2025.3.2
      - idna==3.10
      - jinja2==3.1.6
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - networkx==3.2.1
      - numpy==1.26.4
      - packaging==25.0
      - pandas==2.2.3
      - psutil==7.0.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - requests==2.32.3
      - scipy==1.13.1
      - six==1.17.0
      - sympy==1.13.3
      - torch==2.1.2+cu118
      - tqdm==4.67.1
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - urllib3==2.4.0
